name: README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    name: Fix Readme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run script
        run: |
        chmod +x .github/fix-readme.sh
        .github/fix-readme.sh

      - name: Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "chore(docs): Update README.md" || exit 0   # do not error if nothing to commit
          git push